export const INVOICE_PAGE_SIZE = 20;

export const FETCH_INVOICES = 'FETCH_INVOICES';
export const RESET_INVOICES = 'RESET_INVOICES';
export const FETCH_INVOICES_REQUEST = 'FETCH_INVOICES_REQUEST';
export const FETCH_INVOICES_SUCCESS = 'FETCH_INVOICES_SUCCESS';
export const FETCH_INVOICES_FAILURE = 'FETCH_INVOICES_FAILURE';
export const FETCH_INVOICES_DONE = 'FETCH_INVOICES_DONE';
export const REACHED_END_INVOICES = 'REACHED_END_INVOICES';
