export const INVOICE_PAGE_SIZE = 20;

export const RANGE_LABELS = {
    1: 'MONTH',
    3: 'THREE MONTHS',
    6: 'SIX MONTHS',
    12: 'YEAR'
};

export const FETCH_INVOICES_REQUEST = 'FETCH_INVOICES_REQUEST';
export const FETCH_INVOICES_FAILURE = 'FETCH_INVOICES_FAILURE';
export const FETCH_INVOICES_SUCCESS = 'FETCH_INDEX_INVOICES_SUCCESS';
export const FETCH_INVOICES_DONE = 'FETCH_INVOICES_DONE';

export const RESET_INVOICES = 'RESET_INVOICES';

export const FETCH_INVOICES_COUNT = 'FETCH_INVOICES_COUNT';
export const FETCH_INVOICES_COUNT_SUCCESS = 'FETCH_INVOICES_COUNT_SUCCESS';

export const FETCH_INDEX_INVOICES = 'FETCH_INDEX_INVOICES';

export const FETCH_BRAND_INVOICES = 'FETCH_BRAND_INVOICES';

export const FETCH_CUSTOMER_INVOICES = 'FETCH_CUSTOMER_INVOICES';

export const colors = ['#e6194b', '#3cb44b', '#ffe119', '#4363d8', '#f58231', '#911eb4', '#46f0f0', '#f032e6', '#bcf60c', '#fabebe', '#008080', '#e6beff', '#9a6324', '#fffac8', '#800000', '#aaffc3', '#808000', '#ffd8b1', '#000075', '#808080', '#ffffff', '#000000'];
