export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';
export const SEARCH_DONE = 'SEARCH_DONE';

export const INIT_SEARCH = 'INIT_SEARCH';

export const FETCH_BRANDS = 'FETCH_BRANDS';
export const FETCH_BRANDS_SUCCESS = 'FETCH_BRANDS_SUCCESS';

export const FETCH_CUSTOMERS = 'FETCH_CUSTOMERS';
export const FETCH_CUSTOMERS_SUCCESS = 'FETCH_CUSTOMERS_SUCCESS';

export const FETCH_DESTINATION_COUNTRIES = 'FETCH_DESTINATION_COUNTRIES';
export const FETCH_DESTINATION_COUNTRIES_SUCCESS = 'FETCH_DESTINATION_COUNTRIES_SUCCESS';

export const FETCH_PRODUCT_TYPES = 'FETCH_PRODUCT_TYPES';
export const FETCH_PRODUCT_TYPES_SUCCESS = 'FETCH_PRODUCT_TYPES_SUCCESS';

export const FETCH_TRADERS = 'FETCH_TRADERS';
export const FETCH_TRADERS_SUCCESS = 'FETCH_TRADERS_SUCCESS';
