export const SEARCH_REQUEST = 'SEARCH_REQUEST';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';
export const SEARCH_DONE = 'SEARCH_DONE';

export const INIT_SEARCH = 'INIT_SEARCH';

export const FETCH_BRANDS_SUCCESS = 'FETCH_BRANDS_SUCCESS';

export const FETCH_CUSTOMERS_SUCCESS = 'FETCH_CUSTOMERS_SUCCESS';

export const FETCH_DESTINATION_COUNTRIES_SUCCESS = 'FETCH_DESTINATION_COUNTRIES_SUCCESS';

export const FETCH_PRODUCT_TYPES_SUCCESS = 'FETCH_PRODUCT_TYPES_SUCCESS';

export const FETCH_TRADERS_SUCCESS = 'FETCH_TRADERS_SUCCESS';

export const RESET_CUSTOMER_INFO = 'RESET_CUSTOMER_INFO';

export const FETCH_CUSTOMER_INFO = 'FETCH_CUSTOMER_INFO';
export const FETCH_CUSTOMER_INFO_SUCCESS = 'FETCH_CUSTOMER_INFO_SUCCESS';
